# Generated by Django 5.2.8 on 2025-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration_minutes",
            field=models.DurationField(default=0),
        ),
    ]
