# Generated by Django 5.2.8 on 2025-11-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_movie_duration_minutes_show_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="core.movie",
            ),
        ),
    ]
