# Generated by Django 5.2.8 on 2025-11-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_show_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show",
                to="core.movie",
            ),
        ),
    ]
